"""productos activo y foto

Revision ID: a10499b448a0
Revises: 0400b0515d57
Create Date: 2026-08-14 17:05:17.265770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10499b448a0'
down_revision: Union[str, Sequence[str], None] = '0400b0515d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('foto', sa.String(length=255), nullable=True))
    op.add_column('productos', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'activo')
    op.drop_column('productos', 'foto')
    # ### end Alembic commands ###
